### ISSUE TITLE
Multiple textures - a bug or a gap in description?

### ISSUE THREAD

**Issue by dy** [stackgl/gl-shader-core#14]
Hi @mikolalysenko!

Awesome module, thanks for that.
There are some gaps in readme, in particular, it is not completely clear how user is supposed to pass textures to shaders. I could’ve done it in PR, but I don’t know that info either, heh.

**Comment by dfcreative** [comment]
I’m afraid it can have a bug related with that.
After creating a shader I tried to pass multiple textures as that:

```js
var sourceLocation = gl.getUniformLocation(shader.handle, "source");
var noiseLocation = gl.getUniformLocation(shader.handle, "noise");
gl.uniform1i(sourceLocation, 0);
gl.uniform1i(noiseLocation, 1);
gl.activeTexture(gl.TEXTURE0);
gl.bindTexture(gl.TEXTURE_2D, sourceTexture);
gl.activeTexture(gl.TEXTURE1);
gl.bindTexture(gl.TEXTURE_2D, noiseTexture);
```

And got an error that location is from the different program.

**Comment by dfcreative** [comment]
Oh, seems I’ve forgotten to make `shader.bind();`

**Comment by mikolalysenko** [comment]
Cool, going to close this for now then
